schedule_push/config/routes.rb
Rails.application.routes.draw do
  resources :weeks
  # ------------------------------- Devise Routes -------------------------------------- #
  devise_for :users, skip: [:registrations]

  # ----------------------------------  Route ------------------------------------------ # 
  root to: "users#home"

  # ------------------------- Root when exist Current User ----------------------------- #
  resources :teacher_by_matters
  resources :matters
  resources :scheduleds
  resources :semesters
  resources :rooms
  resources :notifications
  resources :devices
  resources :apps
  resources :rols
  resources :users

  # -------------------------------------- Matches -------------------------------------- #
  match '/home', to: 'users#home', via: :get, as: :home
  match '/users', to: 'users#index', via: :get, as: :users_index

  namespace :api do
    namespace :v1 do
      match 'sign_in/mobile', to: 'users#sign_in_user', via: :post
      match 'return/matters', to: 'users#get_matters', via: :post
    end
  end
end

schedule_push/app/models/device.rb
class Device < ActiveRecord::Base
  # ---------------------- relations -------------------- #
  belongs_to :app
  belongs_to :user # the relation with user is one - one
  has_many :notifications

  # --------------------- validations ------------------- #
  validates :token, presence:{message:'no entered.'}, uniqueness:{message:'already exists!'}
  validates :installation_id, presence:{message:'no entered.'}, uniqueness:{message:'already exists!.'}
  validates :app_id, presence:{message:'no entered.'}

  # ------------------------ scopes --------------------- #

  # ----------------------- methods --------------------- #
  include PermissionsConcern
end

schedule_push/app/controllers/devices_controller.rb
class DevicesController < ApplicationController
  before_action :set_device, only: [:edit, :update, :destroy]
  before_action :get_apps, only: [:new, :edit, :create, :update]

  # GET /devices
  def index
    @devices = Device.order(:installation_id)
  end

  # GET /devices/new
  def new
    @device = Device.new
  end

  # GET /devices/1/edit
  def edit
  end

  # POST /devices
  def create
    @device = Device.new(device_params)

    respond_to do |format|
      if @device.save
        format.html { redirect_to devices_path, notice: 'Device was successfully created.' }
        format.json { render :index, status: :created, location: @device }
      else
        format.html { render :new }
        format.json { render json: @device.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /devices/1
  def update
    respond_to do |format|
      if @device.update(device_params)
        format.html { redirect_to devices_path, notice: 'Device was successfully updated.' }
        format.json { render :index, status: :ok, location: @device }
      else
        format.html { render :edit }
        format.json { render json: @device.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /devices/1
  def destroy
    @device.destroy
    respond_to do |format|
      format.html { redirect_to devices_url, notice: 'Device was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # use for return all apps
    def get_apps
      @apps = App.order(:name)      
    end
    # Use callbacks to share common setup or constraints between actions.
    def set_device
      @device = Device.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def device_params
      params.require(:device).permit(:token, :installation_id, :app_id)
    end
end

schedule_push/app/views/devices/_form.html.erb
<div class="container w100">
  <div class="row w80">
    <%= link_to '<i class="fa fa-arrow-left fs12 tcw"></i>'.html_safe, devices_path, class:'pull-right inlb' %>
    <div class="title-content inlb">
      <h3><%= title %></h3>
    </div>
    <div class="col-md-12">
      <div class="ls1 col-md-10 offset-md-1 pd20">
        <%= form_for(@device, html:{class:'bg10 pd10 bd10 col-md-8 offset-md-2'}) do |f| %>
          <%= render 'layouts/errors', object: @device %>
          <div class="input-group mb-2 mr-sm-2">
            <div class="input-group-addon"><i class="fa fa-sort-numeric-asc tcbl fs10"></i> </div>
            <%= f.text_field :token, class:'form-control bd1 validate_length', placeholder:'Token', required: true, autofocus: true, maxlength:'20' %>
          </div>

          <div class="input-group mb-2 mr-sm-2">
            <div class="input-group-addon"><i class="fa fa-tag tcbl fs10"></i> </div>
            <%= f.text_field :installation_id, class:'form-control bd1 validate_length', placeholder:'Installation ID', required: true, maxlength:'20' %>
          </div>

          <div class="input-group mb-2 mr-sm-2">
            <div class="input-group-addon pd-icon"><i class="fa fa-mobile tcbl fs14"></i> </div>
            <%= f.select :app_id, options_for_select(@apps.collect{|a| [a.name, a.id]}, @device.app_id), {prompt:'Select App'}, {class:'form-control bd1 fs11', required: true, style:'height: 32px;'} %>
          </div>

          <div class="form-group">
            <%= f.submit 'Submit', class:'btn btn-primary btn-sm btn-bordered btn-block ds1' %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

schedule_push/app/views/devices/edit.html.erb
<%= render 'form', title:'Edit Device' %>

schedule_push/app/views/devices/index.html.erb
<div class="container w100">
  <div class="row">
    <div class="col-md-12">
      <%= render 'layouts/notice_mvc' %>
      <div class="col-md-12">
        <h1 class="pull-left mb4">Listing Devices</h1>
        <%= link_to 'New Device', new_device_path, class:'btn btn-primary btn-sm pull-right tcw mb4' %>
      </div>
      <div class="col-md-10 offset-md-1">
        <table class="table table-hover table-sm mt5">
          <thead>
            <tr>
              <th>Token</th>
              <th>Installation</th>
              <th>App</th>
              <th colspan="3"></th>
            </tr>
          </thead>
          <tbody>
            <% @devices.each do |device| %>
              <tr>
                <td><%= device.token.first(10) %></td>
                <td><%= device.installation_id.first(10) %></td>
                <td><%= device.app.name %></td>
                <td><%= link_to "<i class='fa fa-pencil fs13'></i>".html_safe, edit_device_path(device), class:'tcw fs10', :'data-toggle'=>'tooltip', title:'EDITAR' %></td>
                <td><%= link_to "<i class='fa fa-trash fs13'></i>".html_safe, device, method: :delete, data: { confirm: 'Estas Segur@ ?' }, class:'tcw fs10', :'data-toggle'=>'tooltip', title:'ELIMINAR' %></td>
              </tr>
            <% end %>
          </tbody>
          <% if @devices.count > 5 %>
            <tfoot class="bg10 bd4">
              <tr>
                <th>Token</th>
                <th>Installation</th>
                <th>App</th>
                <th colspan="3"></th>
              </tr>
            </tfoot>
          <% end %>
        </table>
      </div>
    </div>
  </div>
</div>

schedule_push/app/views/devices/new.html.erb
<%= render 'form', title:'New Device' %>