schedule_push/config/routes.rb
Rails.application.routes.draw do
  resources :weeks
  # ------------------------------- Devise Routes -------------------------------------- #
  devise_for :users, skip: [:registrations]

  # ----------------------------------  Route ------------------------------------------ # 
  root to: "users#home"

  # ------------------------- Root when exist Current User ----------------------------- #
  resources :teacher_by_matters
  resources :matters
  resources :scheduleds
  resources :semesters
  resources :rooms
  resources :notifications
  resources :devices
  resources :apps
  resources :rols
  resources :users

  # -------------------------------------- Matches -------------------------------------- #
  match '/home', to: 'users#home', via: :get, as: :home
  match '/users', to: 'users#index', via: :get, as: :users_index

  namespace :api do
    namespace :v1 do
      match 'sign_in/mobile', to: 'users#sign_in_user', via: :post
      match 'return/matters', to: 'users#get_matters', via: :post
    end
  end
end

schedule_push/app/models/scheduled.rb
class Scheduled < ActiveRecord::Base
	# ---------------------- relations -------------------- #
	belongs_to :teacher_by_matter
	belongs_to :week

	# --------------------- validations ------------------- #
	validates :block, presence:{message:'no entered.'}, numericality:{only_integer: true, message:'should to be number.'}
	validates :start_hour, presence:{message:'no entered.'}, numericality:{only_integer: true, message:'should to be number.'}
	validates :teacher_by_matter, presence:{message:'no entered.'}
	validates :week_id, presence:{message:'no entered.'}

	# ------------------------ scopes --------------------- #

	# ----------------------- methods --------------------- #
	include PermissionsConcern
end

schedule_push/app/controllers/scheduleds_controller.rb
class ScheduledsController < ApplicationController
  before_action :set_scheduled, only: [:edit, :update, :destroy]
  before_action :set_resources, only: [:new, :edit, :create, :update]

  # GET /scheduleds
  def index
    @scheduleds = Scheduled.order(:block)
  end

  # GET /scheduleds/new
  def new
    @scheduled = Scheduled.new
    @scheduled_hours = @scheduled.scheduled_hours
  end

  # GET /scheduleds/1/edit
  def edit
    @scheduled_hours = @scheduled.scheduled_hours
  end

  # POST /scheduleds
  def create
    @scheduled = Scheduled.new(scheduled_params)

    respond_to do |format|
      if @scheduled.save
        format.html { redirect_to scheduleds_path, notice: 'Scheduled was successfully created.' }
        format.json { render :index, status: :created, location: @scheduled }
      else
        @scheduled_hours = @scheduled.scheduled_hours
        format.html { render :new }
        format.json { render json: @scheduled.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /scheduleds/1
  def update
    respond_to do |format|
      if @scheduled.update(scheduled_params)
        format.html { redirect_to scheduleds_path, notice: 'Scheduled was successfully updated.' }
        format.json { render :index, status: :ok, location: @scheduled }
      else
        @scheduled_hours = @scheduled.scheduled_hours
        format.html { render :edit }
        format.json { render json: @scheduled.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /scheduleds/1
  def destroy
    @scheduled.destroy
    respond_to do |format|
      format.html { redirect_to scheduleds_url, notice: 'Scheduled was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

    # Use callbacks to share common setup or constraints between actions.
    def set_scheduled
      @scheduled = Scheduled.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def scheduled_params
      params.require(:scheduled).permit(:block, :start_hour, :week_id, :teacher_by_matter_id)
    end

    # use for get teacher by matters to select
    def set_resources
      @teacher_by_matters = TeacherByMatter.all
      @weeks = Week.order(:number_day)
    end
end

schedule_push/app/views/scheduleds/_form.html.erb
<div class="container w100">
  <div class="row w80">
    <%= link_to '<i class="fa fa-arrow-left fs12 tcw"></i>'.html_safe, scheduleds_path, class:'pull-right inlb' %>
    <div class="title-content inlb">
      <h3><%= title %></h3>
    </div>
    <div class="col-md-12">
      <div class="ls1 col-md-10 offset-md-1 pd20">
        <%= form_for(@scheduled, html:{class:'bg10 pd10 bd10 col-md-8 offset-md-2'}) do |f| %>
          <%= render 'layouts/errors', object: @scheduled %>
          <label class="sr-only mt5" for="scheduled_block">Block</label>
          <div class="input-group mb-2 mr-sm-2">
            <div class="input-group-addon"><i class="fa fa-sort-numeric-asc tcbl fs12"></i> </div>
            <%= f.number_field :block, class:'form-control bd1 validate_length', placeholder:'Block', required: true, maxlength:'1', autofocus: true %>
          </div>

          <label class="sr-only mt5" for="scheduled_start_hour">Hour</label>
          <div class="input-group mb-3 mr-sm-2">
            <div class="input-group-addon pd-icon"><i class="fa fa-suitcase tcbl fs10"></i></div>
            <%= f.select :start_hour, options_for_select(@scheduled_hours, @scheduled.start_hour), {prompt:'Select Initial Hour'}, {class:'form-control bd1', required: true, style:'height: 30px;'} %>
          </div>

          <div class="input-group mb-3 mr-sm-2">
            <div class="input-group-addon pd-icon"><i class="fa fa-suitcase tcbl fs10"></i></div>
            <%= f.select :teacher_by_matter_id, options_for_select(@teacher_by_matters.collect{|r| [r.teacher_with_matter, r.id]}, @scheduled.teacher_by_matter_id), {prompt:'Select Scheduled'}, {class:'form-control bd1', required: true, style:'height: 30px;'} %>
          </div>

          <div class="input-group mb-3 mr-sm-2">
            <div class="input-group-addon pd-icon"><i class="fa fa-suitcase tcbl fs10"></i></div>
            <%= f.select :week_id, options_for_select(@weeks.collect{|r| [r.week_day, r.id]}, @scheduled.week_id), {prompt:'Select Week Day'}, {class:'form-control bd1', required: true, style:'height: 30px;'} %>
          </div>

          <div class="form-group">
            <%= f.submit 'Submit', class:'btn btn-primary btn-sm btn-bordered btn-block ds1' %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

schedule_push/app/views/scheduleds/edit.html.erb
<%= render 'form', title:'Edit Scheduled' %>

schedule_push/app/views/scheduleds/index.html.erb
<div class="container w100">
  <div class="row">
    <div class="col-md-12">
      <%= render 'layouts/notice_mvc' %>
      <div class="col-md-12">
        <h1 class="pull-left mb4">Listing Scheduleds</h1>
        <%= link_to 'New Scheduled', new_scheduled_path, class:'btn btn-primary btn-sm pull-right tcw mb4' %>
      </div>
      <div class="col-md-10 offset-md-1 mt5">
        <table class="table table-hover table-sm mt5">
          <thead>
            <tr>
              <th>Block</th>
              <th>Hour</th>
              <th>Week Day</th>
              <th>Teacher - Matter</th>
              <th colspan="3"></th>
            </tr>
          </thead>
          <tbody>
            <% @scheduleds.each do |scheduled| %>
              <tr>
                <td><%= scheduled.block %></td>
                <td><%= scheduled.start_hour.to_s.insert(1, ':') %></td>
                <td><%= scheduled.teacher_by_matter.teacher_with_matter if scheduled.teacher_by_matter.present? %></td>
                <td><%= scheduled.week.week_day if scheduled.week.present? %></td>
                <td><%= link_to "<i class='fa fa-pencil fs13'></i>".html_safe, edit_scheduled_path(scheduled), class:'tcw fs10', :'data-toggle'=>'tooltip', title:'EDITAR' %></td>
                <td><%= link_to "<i class='fa fa-trash fs13'></i>".html_safe, scheduled, method: :delete, data: { confirm: 'Estas Segur@ ?' }, class:'tcw fs10', :'data-toggle'=>'tooltip', title:'ELIMINAR' %></td>
              </tr>
            <% end %>
          </tbody>
          <% if @scheduleds.count > 8 %>
            <tfoot class="bg10 bd4">
              <tr>
                <th>Block</th>
                <th>Hour</th>
                <th>Week Day</th>
                <th>Teacher - Matter</th>
                <th colspan="3"></th>
              </tr>
            </tfoot>
          <% end %>
        </table>
      </div>
    </div>
  </div>
</div>

schedule_push/app/views/scheduleds/new.html.erb
<%= render 'form', title:'New Scheduled' %>