schedule_push/config/routes.rb
Rails.application.routes.draw do
  resources :weeks
  # ------------------------------- Devise Routes -------------------------------------- #
  devise_for :users, skip: [:registrations]

  # ----------------------------------  Route ------------------------------------------ # 
  root to: "users#home"

  # ------------------------- Root when exist Current User ----------------------------- #
  resources :teacher_by_matters
  resources :matters
  resources :scheduleds
  resources :semesters
  resources :rooms
  resources :notifications
  resources :devices
  resources :apps
  resources :rols
  resources :users

  # -------------------------------------- Matches -------------------------------------- #
  match '/home', to: 'users#home', via: :get, as: :home
  match '/users', to: 'users#index', via: :get, as: :users_index

  namespace :api do
    namespace :v1 do
      match 'sign_in/mobile', to: 'users#sign_in_user', via: :post
      match 'return/matters', to: 'users#get_matters', via: :post
    end
  end
end

schedule_push/app/views/apps/_form.html.erb
<div class="container w100">
  <div class="row w80">
    <%= link_to '<i class="fa fa-arrow-left fs12 tcw"></i>'.html_safe, apps_path, class:'pull-right inlb' %>
    <div class="title-content inlb">
      <h3><%= title %></h3>
    </div>
    <div class="col-md-12">
      <div class="ls1 col-md-10 offset-md-1 pd20">
        <%= form_for(@app, html:{class:'bg10 pd10 bd10 col-md-8 offset-md-2'}) do |f| %>
          <%= render 'layouts/errors', object: @app %>
          <label class="sr-only mt5" for="app_name">Name</label>
          <div class="input-group mb-2 mr-sm-2">
            <div class="input-group-addon"><i class="fa fa-sort-numeric-asc tcbl fs12"></i> </div>
            <%= f.text_field :name, class:'form-control bd1', placeholder:'Name', required: true, autofocus: true %>
          </div>

          <label class="sr-only mt5" for="app_api_key">Api Key</label>
          <div class="input-group mb-2 mr-sm-2">
            <div class="input-group-addon"><i class="fa fa-tag tcbl fs12"></i> </div>
            <%= f.text_field :api_key, class:'form-control bd1 validate_length', placeholder:'Api Key', required: true, maxlength:'60' %>
          </div>

          <div class="form-group">
            <%= f.submit 'Submit', class:'btn btn-primary btn-sm btn-bordered btn-block ds1' %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

schedule_push/app/views/apps/edit.html.erb
<%= render 'form', title:'Edit App' %>

schedule_push/app/views/apps/index.html.erb
<div class="container w100">
  <div class="row">
    <div class="col-md-12">
      <%= render 'layouts/notice_mvc' %>
      <div class="col-md-12">
        <h1 class="pull-left mb4">Listing Apps</h1>
        <%= link_to 'New App', new_app_path, class:'btn btn-primary btn-sm pull-right tcw mb4' %>
      </div>
      <div class="col-md-10 offset-md-1">
        <table class="table table-hover table-sm mt5">
          <thead>
            <tr>
              <th>Name</th>
              <th>Client Key</th>
              <th>Api Key</th>
              <th colspan="3"></th>
            </tr>
          </thead>
          <tbody>
            <% @apps.each do |app| %>
              <tr>
                <td><%= app.name %></td>
                <td><%= app.client_key.first(30) %></td>
                <td><%= app.api_key.first(30) %></td>
                <td><%= link_to "<i class='fa fa-pencil fs13'></i>".html_safe, edit_app_path(app), class:'tcw fs10', :'data-toggle'=>'tooltip', title:'EDITAR' %></td>
                <td><%= link_to "<i class='fa fa-trash fs13'></i>".html_safe, app, method: :delete, data: { confirm: 'Estas Segur@ ?' }, class:'tcw fs10', :'data-toggle'=>'tooltip', title:'ELIMINAR' %></td>
              </tr>
            <% end %>
          </tbody>
          <% if @apps.count > 5 %>
            <tfoot class="bg10 bd4">
              <tr>
                <th>Name</th>
                <th>Client Key</th>
                <th>Api Key</th>
                <th colspan="3"></th>
              </tr>
            </tfoot>
          <% end %>
        </table>
      </div>
    </div>
  </div>
</div>

schedule_push/app/views/apps/new.html.erb
<%= render 'form', title:'New App' %>